# Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [1]:
import numpy as np
val=np.arange(12,38)
print(val)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# Exercise 2: Add a border around an existing array

In [7]:
x=np.ones((3,3))
print("original array: \n",x)
x= np.pad(x, pad_width=1, mode='constant', constant_values=0)
print("0 on the border and 1 inside the array: \n",x)

original array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside the array: 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Exercise 3: Convert a list and tuple into arrays

In [9]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: \n",np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: \n",np.asarray(my_tuple))



List to array: 
 [1 2 3 4 5 6 7 8]
Tuple to array: 
 [[8 4 6]
 [1 2 3]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees

In [10]:
given_val = [0, 12, 45.21, 34, 99.91]
F = np.array(given_val)
print("Values in Fahrenheit degrees:",F)
print("Values in  Centigrade degrees:",5*F/9 - 5*32/9) 



Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [11]:
arr = np.array([1,1,1], dtype=np.float64)
print("Size of the array: ", arr.size)
print("Length of one array element in bytes: ", arr.itemsize)
print("Total bytes consumed by the elements of the array: ", arr.nbytes)


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


# Exercise 6: Get the unique elements of an array

In [14]:
arr1 = np.array([10, 10, 20, 20, 30, 30])
print("Original array:\n",arr1)
print("Unique elements of the above array:\n",np.unique(arr1))
arr1 = np.array([[1, 1], [2, 3]])
print("Original array:\n",arr1)
print("Unique elements of the above array:\n",np.unique(arr1))

Original array:
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


# Exercise 7: Change the dimension of an array

In [16]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print("original array:",arr2)
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
arr2.shape = (3, 3)
print(arr2)

original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [17]:
arr3 = np.linspace(2.5, 6.5, 30)
print(arr3)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


# Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [19]:
array1 = np.array((10,20,30))
print("Array1:",array1)
array2 = np.array((40,50,60))
print("Array2:",array2)
converted_array = np.column_stack((array1, array2))
print("converted array: \n",converted_array)



Array1: [10 20 30]
Array2: [40 50 60]
converted array: 
 [[10 40]
 [20 50]
 [30 60]]


# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [23]:
a = np.zeros((5,5))
print("Original array: \n",a)
print("Row values ranging from 0 to 4: \n")
a += np.arange(5)
print(a)

Original array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4: 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [29]:
x = np.arange(1, 100)
print("multiple of 3 or 5: ")
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
print("sum of these numbers : \n",n.sum())

multiple of 3 or 5: 
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
sum of these numbers : 
 2318


# Exercise 12: Combine a one and a two dimensional array together and display their elements

In [32]:
aa = np.arange(4)
print("One dimensional array: \n",aa)
bb = np.arange(8).reshape(2,4)
print("Two dimensional array: \n",bb)
for xx, yy in np.nditer([aa,bb]):
    print("%d:%d" % (xx,yy))
    
    


One dimensional array: 
 [0 1 2 3]
Two dimensional array: 
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [34]:
o_arr = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array: \n",o_arr)
print("Replace all elements of the said array with .5 which are greater than .5")
o_arr[o_arr > .5] = .5
print(o_arr)

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


# Exercise 14: Add a new row to an empty numpy array

In [41]:
arr = np.empty((0,3),int)
print("Empty array:")
print(arr)
arr = np.append(arr, np.array([[10,20,30]]),axis=0)
arr = np.append(arr, np.array([[40,50,60]]),axis=0)
print("After adding two new arrays:")
print(arr)

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis

In [50]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([2, 3, 4])
print("Original arrays: \n",array_1,array_2)
print("Sequence of arrays along a new axis:")
print(np.vstack((array_1, array_2)))
array_1 = np.array([[1], [2], [3]])
array_2 = np.array([[2], [3], [4]])
print("Original arrays:\n")
print(array_1)
print()
print(array_2)
print("Sequence of arrays along a new axis:")
print(np.vstack((array_1, array_2)))

Original arrays: 
 [1 2 3] [2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
Original arrays:

[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
